services:
  postgres:
    restart: always
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    ports:
      - '5432'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network

  short-url:
    restart: always
    build: .
    ports:
      - '8090:8090'
    networks:
      - network
    depends_on:
      - postgres

networks:
  network:
    driver: bridge
