life:
  url: 10

server:
  port: 8090

logging:
  level:
    org.springframework: INFO

spring:
  application:
    name: ShortUrl
  datasource:
    url: ${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
