life:
  url: 10

server:
  port: 8090

spring:
  application:
    name: ShortUrl
  datasource:
    url: jdbc:postgresql://postgres:5432/short_url
    username: admin
    password: password_admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
